ORG 0000H
	MOV A , #12H ; FIRST NUMBER
	MOV B , #12H ; SECOND NUMBER 
	MUL AB ; MULTIPLY AB 
	MOV 56H , A ;LOWER BIT 
	MOV 55H , B ; UPPER BIT 
	; lets do again with different value 
	MOV A , #10H ; FIRST NUMBER
	MOV B , #10H ; SECOND NUMBER 
	MUL AB ; MULTIPLY AB 
	MOV 56H , A ;LOWER BIT 
	MOV 55H , B ; UPPER BIT 
	END