ORG 0000H 
	MOV A , #44H 
	MOV B , #11H 
	DIV AB ;  DIVIDE A/B 
	MOV 55H , A ; A = QUOTIENT
	MOV 56H , B ; B = REMAINDER 
	; LET'S TRY AGIAN WITH THE NUMBERS WHICH CAN'T BE DIVIDED COMPLETELY AND WILL HAVE A REMAINDER 
	MOV A , #12H 
	MOV B, #05H 
	DIV AB ; 
	MOV 58H , A 
	MOV 59H  , B 
	END