ORG 0000H 
	CLR C ; BETTER TO DO THIS BEFORE PERFORMING SUBTRACTION 
	MOV A , #12H
	SUBB A , #1H
	MOV 55H , A 
	MOV A , #20H
	SUBB A , #15H ; SUBTRCT HIGH BYTE WITH THE POSSIBLE BORROW 
	MOV 56H , A 
	END