ORG 0000H
	SETB P1.2 ; SET PORT 1 PIN 2 = 1 (TURN IT ON , MAYBE SOME LED OR MOTOOR OR SOMETHING WILL BE THERE ) 
	JB P3.3 , TARGET ; JUMP IF BIT ( P3,3 ) = 1-> MOVE TO TARGET
	THIS: CLR P1.2 ; IF NOT JUMP CLEAR  P1.2
	SETB P3.3 ; 
	TARGET:  CLR P3.3
	JB P1.2 , THIS 
	
	MOV A , #10H
	CLR P2.1 
	JNB P2.1 , OMG
	SEE: ADD A , #10H
	OMG: CPL P2.1 
	JB P2.1 , SEE 
	MOV 55H , A
	JBC P2.1 , SEE ; jump if the bit is set 
	END 